### ISSUE TITLE
Maphper Relation

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#41]
When I am using Maphper and pass an instance to Transphporm and try to access data from a one to one relation an error is issued but when I try to access the data from the relation outside of Transphporm it works

The error is:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'stdClass' does not have a method 'first_name' in C:\Users\admin\OneDrive\Documents\Programing Stuff\Web development\serverRoot\sk_music\lib\maphper\relation\one.php on line 37

**Comment by solleer** [comment]
@TomBZombie 
The problem is in \Transphporm\Hook\DataFunction on line 67 and 68.
For some reason it sees the property as callable on the relation but it is not. So it tries calling the function which results in the error from my previous comment.

**Comment by TomBZombie** [comment]
Can you post your TSS? It'll be interesting to see what is actually being called.

**Comment by solleer** [comment]
```
@import 'layout.tss';

main { content: template('event.xml'); }

@import 'other_layout.tss';

#event { bind: data(event.get_event); }

#time { content: data(time); }


#event .admin a:attr(href) { content: attr(href), data(event_id); }

#event .business_name { content: data(business_name); }
#event .address-label:data[address=false] { display: none; }
#event .address:data[address=false] { display: none; }
#event .address { content: data(address); }

#event .dj { content: 'DJ: ', data(dj.first_name), ' ', data(dj.last_name); }

```

**Comment by TomBZombie** [comment]
Is data() a maphper instance? I see you have event.get_event, is this a relation in maphper or a custom function? What does it return?

**Comment by solleer** [comment]
`event.get_event` returns a maphper instance

**Comment by solleer** [comment]
is_callable returns true because __call is set in the maphper relation

**Comment by TomBZombie** [comment]
I think the only way to resolve this might be explicit function calls using `data(event.getEvent())`

**Comment by solleer** [comment]
That wouldn't be much of a problem for people to change things

**Comment by smolinari** [comment]
> I think the only way to resolve this might be explicit function calls using data(event.getEvent())

Yes! :+1: :smile: 

Scott

**Comment by solleer** [comment]
I read that method_exists could be used to check for __call but I don't know how that would implement in transphporm

**Comment by TomBZombie** [comment]
I think for flexibility going forward the simpler approach is explicit function calls.

**Comment by solleer** [comment]
That makes sense

**Comment by solleer** [comment]
When will it be added

**Comment by TomBZombie** [comment]
This should now work as it uses method_exists instead of is_callable. I've added support for basic explicit function calls with arguments.

You can also do things like:

```css

div { content: data(myFunc(attr(data-foo))); }

```

To pass data from `iteration()`, `attr()` or `data()` as arguments to function calls.

**Comment by solleer** [comment]
An error is no longer issued when accessing the relation but the data still will not display

**Comment by solleer** [comment]
It seems to just print an empty string when anything in the relation is accessed from Transphporm. The relation is successfully accessed outside of Transphporm though.

**Comment by solleer** [comment]
The data from the relation still isn't showing. Also when I try to use repeat on a Maphper instance it doesn't display the data iterations.

**Comment by solleer** [comment]
As a very temporary fix I added `if (isset($value[0]) && $value[0] instanceof \Maphper\Maphper) $value = $value[0];` to line 17 on Transphporm\Property\Repeat. This solved the using repeat on a Maphper instance. Through lots of var_dump-ing I think the Maphper instance kept getting passed in an array with it as the only entry to the repeat class. This is obviously only a temporary fix to allow use of the repeat function without lots of annoying workarounds.

**Comment by solleer** [comment]
I had done the above thing on an older version. It turns out on the most recent version something else broke that I don't know because the function to get the Maphper instance is now returning null though outside of Transphporm it isn't.
